### ISSUE TITLE
It doesn't seem to work

### ISSUE THREAD

**Issue by yurivict** [blablack/deteriorate-lv2#8]
granulator_stereo only passes some outbursts of sound, and downsampler_stereo causes some extra tone when downsampling rate becomes high.

**Comment by blablack** [comment]
Hi,

if you could create different issues in GitHub for different issues you detect that would be great.

To answer the 2 you have:
- Tried granulator_stereo in Ingen and I cannot reproduce what you are mentionning.
- The extra tone in the downsampler are due to the antialiasing not being implemented. This is by design (I wanted a very dirty downsampler) ; there are other downsampler much better implemented around the place.
